# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f7417248fe1ba22cb6998bf119835455106c029464e7147db6c71835a56e77d9de01bd506c94dc28a231b25966e1ffed9291b9a3529f55a9f6ef78ae2112114e

test:
  secret_key_base: 89ea34a4ff72cc982273c597d3114de82c69d6fd253e1f06f7ae9fb4bf46c89fcb857d02974bdc51d0c41ebda4ced5a68f33b8aab6c0d37d4f3c32b652a21ba2

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
